name: multicastSourceListUpdate

on:
  schedule:
      - cron: '0 2 * * 2'  # 每周二凌晨2：00运行一次
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp ffmpeg sed nmap
        pip install --upgrade yt-dlp
        pwd
        which yt-dlp

    - name: Run multicast_all.sh
      run: |
        cd $GITHUB_WORKSPACE/multicastSource
        bash ./multicast_all.sh
        for file in $(find ./ -name '*_-1.txt'); do
          rm -f "$file"
        done
         
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update multicastSource"
        branch: main
