name: newaddress_domestic_fofa

on:
  schedule:
    - cron: "5 6,12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
        pip install --upgrade yt-dlp
        which yt-dlp

    - name: Run addressupdate Script
      #working-directory: iptv/fofa
      run: |
        cd $GITHUB_WORKSPACE/fofa
        bash ./addressupdate.sh
        # bash ./rtp2m3u.sh './zubo_fofa.txt'
        bash ../rtp2m3u.sh domestic.txt
        grep -vE '^#EXTM3U$' ../4gtv.txt >> domestic.m3u         # 这里使用pixman的4gtv补充gangaotai

  
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "Update address in doemstic.txt "
        git push
